version: "3.6"
services:
  app:
    build: .
    volumes:
      - ./:/opt/initial_project
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file:
      - .local.env

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - .local.env
