# Generated by Django 3.0.1 on 2019-12-18 12:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='entity.Entity')),
            ],
        ),
    ]
