# Generated by Django 3.0.1 on 2019-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_entity_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entitydata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
